### ISSUE TITLE
The  detail file

### ISSUE THREAD

**Issue by fangchen1993** [wil3/gymfc#5]
Hello,I want know how you to write this model,do you have some blogs to introduce the gymfc.And when i run the command "python3 -m gymfc.controllers.iris_pid_eval --env-id=AttFC_GyroErr-MotorVel_M4_Ep-v0",I got this error:

`Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/fc/桌面/gymfc-master/gymfc/controllers/iris_pid_eval.py", line 180, in <module>
    main(args.env_id, args.seed)
  File "/home/fc/桌面/gymfc-master/gymfc/controllers/iris_pid_eval.py", line 163, in main
    env = gym.make(env_id)
  File "/home/fc/gym/gym/envs/registration.py", line 167, in make
    return registry.make(id)
  File "/home/fc/gym/gym/envs/registration.py", line 119, in make
    env = spec.make()
  File "/home/fc/gym/gym/envs/registration.py", line 85, in make
    cls = load(self._entry_point)
  File "/home/fc/gym/gym/envs/registration.py", line 14, in load
    result = entry_point.load(False)
  File "/home/fc/gym-duckietown/setuptools-19.6/pkg_resources/__init__.py", line 2370, in load
    return self.resolve()
  File "/home/fc/gym-duckietown/setuptools-19.6/pkg_resources/__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/fc/桌面/gymfc-master/gymfc/envs/__init__.py", line 1, in <module>
    from gymfc.envs.attitude_control_env import GyroErrorFeedbackEnv
  File "/home/fc/桌面/gymfc-master/gymfc/envs/attitude_control_env.py", line 3, in <module>
    from .gazebo_env import GazeboEnv
  File "/home/fc/桌面/gymfc-master/gymfc/envs/gazebo_env.py", line 16, in <module>
    import pygazebo
  File "/usr/local/lib/python3.5/dist-packages/pygazebo-3.0.0_2014.1-py3.5.egg/pygazebo/__init__.py", line 22, in <module>
    from pygazebo import connect
ImportError: cannot import name 'connect'
`

**Comment by wil3** [comment]
Hi, this was addressed in Issue #2, you are using old code, please do a
pull.

Details of GymFC can be found in our paper referenced in the readme.
